"""deleted unique cons

Revision ID: 7d2899731d2e
Revises: 358c7b8cc78c
Create Date: 2024-08-03 12:21:35.613808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d2899731d2e'
down_revision: Union[str, None] = '358c7b8cc78c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tasks_name', table_name='tasks')
    op.create_index(op.f('ix_tasks_name'), 'tasks', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_name'), table_name='tasks')
    op.create_index('ix_tasks_name', 'tasks', ['name'], unique=True)
    # ### end Alembic commands ###
